name: econoengine
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter


 
  cupertino_icons: ^1.0.8
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  get: ^4.6.5
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^4.0.0


flutter:
  assets:
    - assets/images/logo.png

  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icono.png" # Ruta del icono
  adaptive_icon_foreground: "assets/images/icono.png" # Ruta del icono

flutter_native_splash:
  color: "#1A237E"  # Color de fondo (azul acorde a tu aplicación)
  background_image: assets/images/splash.jpg  # Ruta de la imagen vertical
  android: true  # Habilita el splash screen en Android
  ios: true      # Habilita el splash screen en iOS
